<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fourallportal"
 *
 * Auto generated by Extension Builder 2017-08-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '4AllPortal Connector',
    'description' => '',
    'category' => 'be',
    'author' => 'Marc Neuhaus',
    'author_email' => 'marc@mia3.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
