<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fourallportal"
 *
 * Auto generated by Extension Builder 2017-08-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
  'title' => '4AllPortal Connector',
  'description' => '',
  'category' => 'be',
  'version' => '6.0.0-dev',
  'author' => 'Eyad Abdullah',
  'author_email' => 'e.abdullah@4allportal.com',
  'state' => 'alpha',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'clearCacheOnLoad' => 0,
  'constraints' => [
    'depends' => [
      'typo3' => '12.3.0-12.4.99',
    ],
    'conflicts' => [],
    'suggests' => [],
  ],
  'autoload' => [
    'psr-4' => [
      'Crossmedia\\Fourallportal\\' => 'Classes',
    ],
  ],
];
